version: 1.1.0
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: build.cmd
test: off
artifacts:
- path: artifacts\*.nupkg
  name: NuGetPackages
deploy:
- provider: NuGet
  server: https://www.myget.org/F/wiry-net/api/v2/package
  api_key:
    secure: ItL4XEZ+i1DrVYGpgm/fZGZxtOvMBeJnrGluvs7U0Tak7PSQgWmmjqISNY2vxz8x
  skip_symbols: true
  artifact: NuGetPackages